CREATE OR REPLACE FUNCTION validate_email(email text)
  RETURNS text AS
$BODY$
BEGIN
  IF email IS NOT NULL THEN
    IF email !~* '\\A[^@\\s;./[\\]\\\\]+(\\.[^@\\s;./[\\]\\\\]+)*@[^@\\s;./[\\]\\\\]+(\\.[^@\\s;./[\\]\\\\]+)*\\.[^@\\s;./[\\]\\\\]+\\Z' THEN
      RAISE EXCEPTION 'Invalid E-mail format %', email
          USING HINT = 'Please check your E-mail format.';
    END IF ;
    email = lower(email);
  END IF ;

  RETURN email;
END;
$BODY$
LANGUAGE plpgsql;
